1.	Write a Python program to create a NumPy array from a list and print its shape.
o	List = [1, 2, 3, 4, 5, 6]


In [ ]:
import numpy as np
lst = [1, 2, 3, 4, 5, 6]
arr = np.array(lst)
print("NumPy array:", arr)
print("Shape of the array:", arr.shape)


NumPy array: [1 2 3 4 5 6]
Shape of the array: (6,)


2.	Write a Python program to create a NumPy array and print its number of dimensions (ndim).
o	Array = [[1,2,3],[4,5,6]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("NumPy Array:")
print(arr)
print("Number of Dimensions (ndim):", arr.ndim)


NumPy Array:
[[1 2 3]
 [4 5 6]]
Number of Dimensions (ndim): 2


3.	Write a Python program to create a NumPy array and print its total number of elements (size).
o	Array = [10, 20, 30, 40, 50]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("NumPy Array:", arr)
print("Total number of elements (size):", arr.size)


NumPy Array: [10 20 30 40 50]
Total number of elements (size): 5


4.	Write a Python program to find the data type (dtype) of a given NumPy array.
o	Array = [1.0, 2.5, 3.8]


In [ ]:
import numpy as np

arr = np.array([1.0, 2.5, 3.8])

print("NumPy Array:", arr)
print("Data type (dtype):", arr.dtype)


NumPy Array: [1.  2.5 3.8]
Data type (dtype): float64


5.	Write a Python program to convert the data type of a NumPy array from float to int using astype().
o	Array = [5.5, 6.7, 8.9]


In [ ]:
import numpy as np

arr = np.array([5.5, 6.7, 8.9])

# Convert float array to integer array
int_arr = arr.astype(int)

print("Original Array:", arr)
print("Converted Integer Array:", int_arr)
print("Datatype after conversion:", int_arr.dtype)


Original Array: [5.5 6.7 8.9]
Converted Integer Array: [5 6 8]
Datatype after conversion: int64


6.	Write a Python program to create a NumPy array initialized with all zeros of size 4.

In [ ]:
import numpy as np

arr = np.zeros(4)

print("Zero Array:", arr)
print("Shape:", arr.shape)
print("Datatype:", arr.dtype)


Zero Array: [0. 0. 0. 0.]
Shape: (4,)
Datatype: float64


7.	Write a Python program to create a NumPy array initialized with all ones of size (2,3).

In [ ]:
import numpy as np

arr = np.ones((2, 3))

print("Ones Array:")
print(arr)
print("Shape:", arr.shape)
print("Datatype:", arr.dtype)


Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]]
Shape: (2, 3)
Datatype: float64


8.	Write a Python program to create a NumPy array containing numbers from 10 to 30 (excluding 30) using np.arange().

In [ ]:
import numpy as np

arr = np.arange(10, 30)

print("Array from 10 to 30 (excluding 30):")
print(arr)


Array from 10 to 30 (excluding 30):
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


9.	Write a Python program to create a NumPy array of 7 random integers between 0 and 100.

In [ ]:
import numpy as np

arr = np.random.randint(0, 101, size=7)

print("Random Integer Array:", arr)


Random Integer Array: [48 16 77 66 58 55 98]


10.	Write a Python program to create an array with 10 numbers evenly spaced between 0 and 5 using linspace().

In [ ]:
import numpy as np

arr = np.linspace(0, 5, 10)

print("Evenly spaced array:", arr)


Evenly spaced array: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


11.	Write a Python program to create a NumPy array directly from the numbers [11, 22, 33, 44, 55].

In [ ]:
import numpy as np

arr = np.array([11, 22, 33, 44, 55])

print("NumPy Array:", arr)
print("Datatype:", arr.dtype)
print("Shape:", arr.shape)


NumPy Array: [11 22 33 44 55]
Datatype: int64
Shape: (5,)


12.	Write a Python program to create a 1D NumPy array from a given Python list.
o	List = [3, 6, 9, 12, 15]


In [ ]:
import numpy as np

lst = [3, 6, 9, 12, 15]

arr = np.array(lst)

print("1D NumPy Array:", arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)


1D NumPy Array: [ 3  6  9 12 15]
Shape: (5,)
Dimensions: 1


13.	Write a Python program to create a 2D NumPy array from a tuple.
o	Tuple = ((1,2,3),(4,5,6))


In [ ]:
import numpy as np

t = ((1, 2, 3), (4, 5, 6))

arr = np.array(t)

print("2D NumPy Array:")
print(arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)


2D NumPy Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2


14.	Write a Python program to create a 3x3 identity matrix using NumPy.

In [ ]:
import numpy as np

arr = np.eye(3)

print("3x3 Identity Matrix:")
print(arr)


3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


15.	Write a Python program to create a 5x5 array initialized with random floats between 0 and 1.

In [ ]:
import numpy as np

arr = np.random.rand(5, 5)

print("5x5 Random Float Array:")
print(arr)


5x5 Random Float Array:
[[0.09668214 0.52323415 0.75834835 0.49448802 0.39087851]
 [0.27546377 0.43583585 0.16342092 0.49519507 0.24560181]
 [0.43971411 0.53509584 0.6933836  0.01813579 0.39423447]
 [0.29918253 0.10421859 0.38197415 0.01237028 0.32508951]
 [0.37047088 0.35603544 0.7196884  0.35728279 0.27577741]]


16.	Write a Python program to create an array of even numbers from 2 to 20 using np.arange().

In [ ]:
import numpy as np

arr = np.arange(2, 21, 2)

print("Array of even numbers from 2 to 20:")
print(arr)


Array of even numbers from 2 to 20:
[ 2  4  6  8 10 12 14 16 18 20]


17.	Write a Python program to create an array with random integers between 50 and 100 and print its shape, size, and dtype.
o	(Array should have 2 rows and 5 columns.)


In [ ]:
import numpy as np

arr = np.random.randint(50, 101, size=(2, 5))

print("Random Integer Array (2x5):")
print(arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Datatype:", arr.dtype)


Random Integer Array (2x5):
[[73 87 66 64 83]
 [64 66 74 94 50]]
Shape: (2, 5)
Size: 10
Datatype: int64


18.	Write a Python program to create an array from existing data [7, 14, 21, 28, 35] and print its number of dimensions.

In [ ]:
import numpy as np

arr = np.array([7, 14, 21, 28, 35])

print("Array:", arr)
print("Number of Dimensions (ndim):", arr.ndim)


Array: [ 7 14 21 28 35]
Number of Dimensions (ndim): 1


19.	Write a Python program to create an array from a list of strings ['apple', 'banana', 'cherry'] and print its data type.

In [ ]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print("Array:", arr)
print("Data type (dtype):", arr.dtype)


Array: ['apple' 'banana' 'cherry']
Data type (dtype): <U6


20.	Write a Python program to create an array of 10 numbers between 1 and 2 using linspace() and print the array.

In [ ]:
import numpy as np

arr = np.linspace(1, 2, 10)

print("Array of 10 numbers between 1 and 2:")
print(arr)


Array of 10 numbers between 1 and 2:
[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
