Array Manipulation
np.transpose(array) - To transpose array
np.reshape(array,shape) - To Change shape of an array
np.resize(array,shape) - To return new array with shape
np.flatten(array) - To flatten the array
np.transpose()
Transpose is defined as an operator which flips a matrix over its diagonal; that is, it switches the row and column indices of the matrix A by producing another matrix, often denoted by  AT
np.reshape(shape)
Gives a new shape to an array without changing its data.
np.resize(shape)
Changes shape and size of array in-place.
np.flatten()
Returns flattened 1D **arrays**

Question 1: Given a 1D NumPy array arr_1d, extract and print the first element.

arr_1d = np.array([1, 2, 3, 4, 5])**bold text**

In [3]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
a = arr_1d[0]
print(a)

1


Question 2: Given a 1D NumPy array arr_1d, extract and print the last three elements.

arr_1d = np.array([1, 2, 3, 4, 5])

In [4]:
arr_1d = np.array([1, 2, 3, 4, 5])
a = arr_1d[2:]
print(a)

[3 4 5]


Question 3: Given a 2D NumPy array arr_2d, extract and print the element at the second row and third column.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)
a = arr_2d[1,2]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


Question 4: Given a 2D NumPy array arr_2d, extract and print the first row.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)
a = arr_2d[:1]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]


Question 5: Given a 2D NumPy array arr_2d, extract and print the last column.



arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)
a = arr_2d[:,2]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6 9]


Question 6: Given a 3D NumPy array arr_3d, extract and print the element at the second matrix, third row, and third column.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [8]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr_3d)
a = arr_3d[1,2,2]
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
18


Question 7: Given a 3D NumPy array arr_3d, extract and print the first matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [9]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr_3d)
a = arr_3d[0]
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Question 8: Given a 3D NumPy array arr_3d, extract and print the last matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [10]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr_3d)
a = arr_3d[1]
a

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

## Question 1: Transpose Array

Given a 2D NumPy array arr_2d, transpose the array and print the result.

Example Input:

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)
a = np.transpose(arr_2d)
print(a)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


Question 2: Reshape Array
Given a 1D NumPy array arr_1d, reshape it into a 3x2 array and print the result.

Example Input:

arr_1d = np.array([1, 2, 3, 4, 5, 6])

In [12]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print(arr_1d)
a = np.reshape(arr_1d, (3,2))
print(a)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


## Question 3: Resize Array
Given a 1D NumPy array arr_1d, resize it into a 3x3 array and print the result.

Example Input:

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])


In [13]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr_1d)
a = np.resize(arr_1d, (3,3))
print(a)

[1 2 3 4 5 6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 1]]


## Question 4: Flatten Array
Given a 2D NumPy array arr_2d, flatten it and print the result.

Example Input:

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])


In [14]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)
a = arr_2d.flatten()
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


Question 5: Transpose Array
Given a 3D NumPy array arr_3d, transpose the array and print the result.

Example Input:

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

In [15]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(arr_3d)
print()
a = np.transpose(arr_3d)
print(a)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

[[[ 1  5  9]
  [ 3  7 11]]

 [[ 2  6 10]
  [ 4  8 12]]]


## Question 6: Reshape Array
Given a 1D NumPy array arr_1d, reshape it into a 4x3 array and print the result.

Example Input:


arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [16]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr_1d)
a = np.reshape(arr_1d,(4,3))
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Question 7: Resize Array
Given a 2D NumPy array arr_2d, resize it into a 4x4 array and print the result.

Example Input:


arr_2d = np.array([[1, 2], [3, 4]])


In [17]:
arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d)
a = np.resize(arr_2d,(4,4))
print(a)

[[1 2]
 [3 4]]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


## Question 8: Flatten Array
Given a 3D NumPy array arr_3d, flatten it and print the result.

Example Input:



arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


In [18]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)
a = arr_3d.flatten()
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
